version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./index.js:/docker-entrypoint-initdb.d/index.js
    restart: always

volumes:
  mongodb-data:

